baseURL = "http://usamasubhani.tech/blog"
languageCode = "en-us"
title = "Usama's Blog"
theme = "hugo-notepadium"

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
slogan = "100% JavaScript-free"
license = ""  # CC License
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.

[[params.nav.custom]]
title = "Home"
url = "#"
